version: "3.0"
services:
  db:
    image: calorie-db-server
    build: .
    volumes:
      - .:/calculator
    ports:
      - "9033:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=F00dieData
    

